### ISSUE TITLE
Archive directory path is ignored

### ISSUE THREAD

**Issue by blazsvigelj** [cocowalla/serilog-sinks-file-archive#13]
When calling `ArchiveHooks` with `retainedFileCountLimit` the target directory is ignored. 

Fore example:
`new ArchiveHooks(3, CompressionLevel.Fastest, "/archive");`
will never move compressed files in `/archive` folder. 

Possible solution:
https://github.com/cocowalla/serilog-sinks-file-archive/blob/d3a20bbba4282284aedd174f25f296ddac097af8/src/Serilog.Sinks.File.Archive/ArchiveHooks.cs#L50

should be `this.targetDirectory = targetDirectory;`

**Comment by cocowalla** [comment]
@blazsvigelj thanks for finding this, it's now been fixed and a new version pushed: https://www.nuget.org/packages/Serilog.Sinks.File.Archive/1.0.3
