### ISSUE TITLE
Serilog.Sinks.File

### ISSUE THREAD

**Issue by SkinnySackboy** [cocowalla/serilog-sinks-file-archive#15]
Hi guys,

Any objections if I create a PR to bump to the latest version of Serilog.Sinks.File?

Cheers

**Comment by cocowalla** [comment]
Is there a good reason to? I don't want to prevent people still on `Serilog.Sinks.File` 4.x from using this plugin. You can of course still use a newer version in your project if you want, by explicitly pulling in the Nuget version you want.

**Comment by SkinnySackboy** [comment]
Mostly to avoid having to apply this workaround.

**Comment by cocowalla** [comment]
I think it makes more sense to just take the transitive dependency from the upstream `Serilog.Sinks.File` project, which [remains at 2.10.0.](https://github.com/serilog/serilog-sinks-file/blob/dev/src/Serilog.Sinks.File/Serilog.Sinks.File.csproj#L31). In that way, we leave it up to the Serilog File Sink to make this decision.
