### ISSUE TITLE
Sign the assembly to get strong-name

### ISSUE THREAD

**Issue by alexasamura** [cocowalla/serilog-sinks-file-archive#3]
Please, sign the assembly Serilog.Sinks.File.Archive to get strong-name so we can pull from Nuget and use this in others applications that already signed.
Thank you.

**Comment by cocowalla** [comment]
I've been using .NET Core for so long that I forgot all about the hell of strong names 😅 

I accept to add it though, thanks for the suggestion!

**Comment by tts-sdrissen** [comment]
If you merge my request and publish it as a new version in nuget, this issue can be closed as fixed. Thank you!

**Comment by tts-sdrissen** [comment]
Thanks for merging my request! This solved my issue.

The issue can be closed as fixed.
