### ISSUE TITLE
Question: why throw exception on NoCompression

### ISSUE THREAD

**Issue by LiorBanai** [cocowalla/serilog-sinks-file-archive#4]
in the following line an exception is thrown when the NoCompression is used.

https://github.com/cocowalla/serilog-sinks-file-archive/blob/8eb08c6f467d290b52f122e24051c3e200d55528/src/Serilog.Sinks.File.Archive/ArchiveHooks.cs#L29

why is that?  a compressed file could be used to store files without compression but it is still valid file?
Am I missing something?

especially when in the OnFileDeleting method there is a check:
  if (this.compressionLevel == CompressionLevel.NoCompression)
 { ..}

**Comment by cocowalla** [comment]
GZIP is not a container format (like ZIP, or a tarball), so a GZIP file only compresses a single file. "no compression" in this plugin therefore doesn't mean "create a compressed file in 'store' mode; rather, it means "don't use any compression" (move the original text file that the sink wrote).

If using compression, it's also valid to store the archived files in the *current* log folder, alongside the live log files. This is the main reason for throwing if no compression is used *and* a different log folder is not specified, as it doesn't make sense to move the original files to the same location.

Hope this makes sense!

**Comment by LiorBanai** [comment]
Thanks, now I understand.
I'm adding support for compressed zip and gz files so I was not ware of this difference.

**Comment by cocowalla** [comment]
I should probably improve the code comment to make the reasoning clearer :smile:
